# Generated by Django 3.1.6 on 2021-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0004_auto_20210319_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarkovitem',
            name='craftingstation',
        ),
        migrations.AddField(
            model_name='tarkovitemhideout',
            name='craftingreqs',
            field=models.JSONField(blank=True, default=dict),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarkovitemhideout',
            name='stationlevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarkovitemhideout',
            name='level1itemcount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarkovitemhideout',
            name='level2itemcount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarkovitemhideout',
            name='level3itemcount',
            field=models.IntegerField(blank=True),
        ),
    ]
