# Generated by Django 3.1.6 on 2021-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0007_tarkovfoundinraid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkovfoundinraid',
            name='quest',
            field=models.CharField(max_length=128),
        ),
    ]
