# Generated by Django 3.1.6 on 2021-03-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0008_auto_20210330_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkovfoundinraid',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoenix.tarkovquesttester'),
        ),
    ]
