# Generated by Django 3.1.6 on 2021-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0009_auto_20210330_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarkovquesttester',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
