# Generated by Django 3.1.6 on 2021-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0011_tarkovqueststructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onquests',
            field=models.ManyToManyField(related_name='onquest', to='phoenix.TarkovQuestTester'),
        ),
    ]
