# Generated by Django 3.1.6 on 2021-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0012_user_onquests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarkovqueststructure',
            name='questgiver',
            field=models.CharField(default='Prapor', max_length=50),
        ),
    ]
