# Generated by Django 3.1.6 on 2021-04-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0013_tarkovqueststructure_questgiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarkovitem',
            name='firquest',
        ),
        migrations.DeleteModel(
            name='TarkovItemQuest',
        ),
        migrations.DeleteModel(
            name='TarkovQuest',
        ),
    ]
