# Generated by Django 3.1.6 on 2021-04-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0014_auto_20210419_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completedquests',
            field=models.ManyToManyField(related_name='completed', to='phoenix.TarkovQuestTester'),
        ),
    ]
